CREATE USER admin1 WITH PASSWORD 'admin' IN GROUP adminadmin SUPERUSER;
CREATE USER admin2 WITH PASSWORD 'admin' IN GROUP adminusuarios;
CREATE USER admin3 WITH PASSWORD 'admin' IN GROUP admininstructores;
CREATE USER admin4 WITH PASSWORD 'admin' IN GROUP adminsesiones;
CREATE USER admin5 WITH PASSWORD 'admin' IN GROUP adminreportes;

SELECT * FROM USUARIO

SELECT * FROM PG_ROLES;

drop user adminprueba1;
DROP USER ADMINPRUEBA2;
DROP USER ADMINPRUEBA3;
DROP USER ADMINPRUEBA4;
DROP USER ADMINPRUEBA5;


DELETE FROM usuario WHERE fechanacimiento = '2111-01-01';